name: "Puppet"
description: "Turn dashboards into nice pictures"
version: "1.10.2"
slug: "puppet"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
options:
  home_assistant_url: "http://localhost:8123"
  access_token: ""
schema:
  home_assistant_url: str
  access_token: str
